{% set name = "azure-mgmt-storage" %}
{% set version = "7.1.0" %}
{% set sha256 = "b4dc00bf960d98e7d03d70737fbccfedfe946b112602b375539a4fde02dfd20f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3
    - setuptools
    - pip
  run:
    - python >=3
    - azure-common >=1.1
    - msrestazure >=0.4.11

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.storage
  commands:
    - python -m unittest discover -p "test_storage_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  summary: 'Microsoft Azure Storage Resource Management Client Library for Python'

extra:
  recipe-maintainers:
    - ivoflipse
    - Maxyme
