{% set name = "azure-mgmt-storage" %}
{% set version = "21.0.0" %}
{% set sha256 = "6eb13eeecf89195b2b5f47be0679e3f27888efd7bd2132eec7ebcbce75cb1377" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - msrest >=0.7.1
    - azure-common ~=1.1
    - azure-mgmt-core >=1.3.2,<2.0.0
    - typing_extensions >=4.3.0  # TODO: Remove when py38 is minimum supported

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.storage
  commands:
    - python -m unittest discover -p "test_storage_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-mgmt-storage
  license: MIT
  license_file: LICENSE
  summary: Microsoft Azure Storage Resource Management Client Library for Python

extra:
  recipe-maintainers:
    - dhirschfeld
    - Maxyme
